# Generated by Django 4.2.4 on 2023-08-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingDate',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_guest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
